# Generated by Django 5.2.5 on 2025-08-09 00:25

import core_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insured',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[core_app.validators.validate_cpf]),
        ),
    ]
